language: java
jdk: oraclejdk8
install: true
before_script:
  - chmod +x ./gradlew
script:
  - "./gradlew build --parallel --scan -s"
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
deploy:
  provider: bintray
  user: fangzhengjin
  key:
    secure: meNB3Znq1Atjx1FU8fWWlzjMOVkt9p6KpOO4l1xn/gCcaYyNnex8HIHLTvG1c16O7FGPW5E2o0sN9TkUN3PtilHu6pQ9vr4JQTqAyklDu/cWn+U8yaOA0NjvOHQ3J9LABI8bViLEFRlXx/shjT5g42pR6gCmlLgmbEz/2MXWvASsfePLhnp4d1JqDJOowtN/iPLbq1y9xBxQZmT65RbiLJ9Gohrguh6Eqd3Ou70RKRTtJcKb0J/KGdiVpkX6zFvcs/v6Lyt5QwUtKOYHIpclbXu77mDMEUhY2Gl3rIwgq6mhv8nfPF+YkYewBBrdl7UQgn2P4R3qoHcFBYLj8uwuwhmlYxOHse1n/AgeWKjDA/YxpuV1Y3VxSqZviYucCbVh8MnpwK3K+fS6JbTeq+KeVyP9xWve0u/zGUvx3BwCYbF4xgy/heg6kXZwlNFXaap8Vy7fD1YpzGU1NWvd4j6wa65bwk/tU55Zm92kJoiwBJsOPE3A58mdsOUMSa0Zroxl7kp4IeB4n0GW7Xqjl2R5LgtJyFhyppf4TbIvw6zSmxCmOv3AD/hfChTdI25WgKMJmqoeRxcE9fY5utlz6/j1OCi5mm86hhcDe327ekvNX02C7WEcqDd974O8X3WltRVds1IEjvH/NKxn/dErUiQ7Bsm6YWEsGSgMFvIll4mN9yY=
  skip_cleanup: true
  file: build/descriptor.json
  on:
    tags: true
    jdk: oraclejdk8
    branch: master